# Generated by Django 5.0.3 on 2024-04-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencedata',
            name='link_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
