# Generated by Django 5.0.3 on 2024-04-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0002_alter_experiencedata_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencedata',
            name='link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
