# Generated by Django 5.0.3 on 2024-04-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0005_productsdata_infrastracture_productsdata_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsdata',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
