# Generated by Django 5.0.3 on 2024-04-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0007_rename_detail_productsdata_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsdata',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
