# Generated by Django 5.0.3 on 2024-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0008_productsdata_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=100)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('admin', models.BooleanField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRoomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=20, unique=True)),
                ('auth_code', models.CharField(blank=True, max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('progress', models.BooleanField(default=False)),
                ('close', models.BooleanField(default=False)),
            ],
        ),
    ]
