# Generated by Django 5.0.3 on 2024-05-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0010_remove_contactroomdata_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactroomdata',
            name='close',
            field=models.BooleanField(),
        ),
    ]
