# Generated by Django 4.2.11 on 2024-06-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0011_alter_contactroomdata_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
