# Generated by Django 4.2.11 on 2024-06-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0012_profiledata_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledata',
            name='title',
        ),
    ]
