# Generated by Django 4.2.11 on 2024-07-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0013_remove_profiledata_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsdata',
            name='collaborators',
            field=models.TextField(blank=True),
        ),
    ]
