# Generated by Django 4.2.11 on 2024-07-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0014_productsdata_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencedata',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsdata',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staticprofiledata',
            name='display_image',
            field=models.URLField(default='https://img.somando.jp/icon.webp'),
            preserve_default=False,
        ),
    ]
