# Generated by Django 4.2.11 on 2024-07-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0016_alter_productsdata_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsdata',
            name='link_title',
        ),
        migrations.RemoveField(
            model_name='productsdata',
            name='link_url',
        ),
        migrations.AddField(
            model_name='productsdata',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
