# Generated by Django 4.2.11 on 2024-07-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0017_remove_productsdata_link_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencedata',
            name='link_title',
        ),
        migrations.RemoveField(
            model_name='experiencedata',
            name='link_url',
        ),
        migrations.AddField(
            model_name='experiencedata',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
