# Generated by Django 4.2.11 on 2025-02-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0019_skillcategorydata_skilldata_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilldata',
            name='show_top',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='skillcategorydata',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skilldata',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
