# Generated by Django 4.2.11 on 2025-02-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0020_skilldata_show_top_alter_skillcategorydata_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilldata',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='skilldata',
            name='icon_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
