# Generated by Django 4.2.11 on 2025-02-07 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0021_skilldata_url_alter_skilldata_icon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilldata',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='somando.skillcategorydata'),
        ),
    ]
