# Generated by Django 4.2.11 on 2025-02-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0022_alter_skilldata_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillcategorydata',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='skillcategorydata',
            name='title_ja',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
