# Generated by Django 4.2.11 on 2025-02-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0023_rename_title_skillcategorydata_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillcategorydata',
            name='title_ja',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skilldata',
            name='icon_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skilldata',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
