# Generated by Django 4.2.11 on 2025-02-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('somando', '0024_alter_skillcategorydata_title_ja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilldata',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='somando.skillcategorydata'),
        ),
    ]
